-- =============================================================================
-- Lyrical — replace theme tags with a single required poetry type
-- =============================================================================
-- Depends on 001_initial_schema.sql (already executed). Do not re-run 001.
-- Each poem must have exactly one poetry type. Theme tags are removed.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) poetry_types catalog
-- Controlled catalog data: clients may read only; privileged roles maintain it.
-- -----------------------------------------------------------------------------

create table public.poetry_types (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  created_at timestamptz not null default now(),
  constraint poetry_types_name_unique unique (name),
  constraint poetry_types_slug_unique unique (slug),
  constraint poetry_types_name_length check (char_length(name) between 1 and 60),
  constraint poetry_types_slug_length check (char_length(slug) between 1 and 60)
);

comment on table public.poetry_types is
  'Controlled poetry-form catalog. Spanish name is the display value; English slug is the stable programmatic id. Normal clients cannot write this table.';

comment on column public.poetry_types.name is
  'Spanish display name for the poetry type.';

comment on column public.poetry_types.slug is
  'Stable English identifier used by application code.';

-- -----------------------------------------------------------------------------
-- 2) Seed poetry types (Spanish name / English slug)
-- -----------------------------------------------------------------------------

insert into public.poetry_types (name, slug) values
  ('Verso libre', 'free-verse'),
  ('Soneto', 'sonnet'),
  ('Haiku', 'haiku'),
  ('Poesía en prosa', 'prose-poetry'),
  ('Poesía lírica', 'lyric-poetry'),
  ('Poesía narrativa', 'narrative-poetry'),
  ('Elegía', 'elegy'),
  ('Acróstico', 'acrostic');

-- -----------------------------------------------------------------------------
-- 3) Add poetry_type_id to poems (nullable first for safe backfill)
-- -----------------------------------------------------------------------------

alter table public.poems
  add column poetry_type_id bigint references public.poetry_types (id);

comment on column public.poems.poetry_type_id is
  'Exactly one poetry type per poem. Immutable after submission for normal clients.';

-- Development-safe backfill: if poems already exist without a type, assign
-- Verso libre (free-verse) temporarily so NOT NULL can be applied.
do $$
declare
  existing_poems integer;
  free_verse_id bigint;
begin
  select count(*)::integer into existing_poems from public.poems;

  select pt.id
  into strict free_verse_id
  from public.poetry_types pt
  where pt.slug = 'free-verse';

  if existing_poems > 0 then
    update public.poems
    set poetry_type_id = free_verse_id
    where poetry_type_id is null;
  end if;
end;
$$;

alter table public.poems
  alter column poetry_type_id set not null;

-- Ensure no lingering default: new poems must supply poetry_type_id explicitly.
alter table public.poems
  alter column poetry_type_id drop default;

create index poems_poetry_type_id_idx on public.poems (poetry_type_id);

comment on table public.poems is
  'Poems start as pending and require exactly one poetry_type_id. Moderation status is separate from author hide/soft-delete. Clients cannot change poetry type after submission.';

-- -----------------------------------------------------------------------------
-- 4) Remove the old theme-tag system (no CASCADE)
-- Drop dependents in order: policies → trigger → function → grants → tables.
-- -----------------------------------------------------------------------------

drop policy if exists "poem_tags_select_public_or_author" on public.poem_tags;
drop policy if exists "poem_tags_insert_own_pending" on public.poem_tags;
drop policy if exists "poem_tags_delete_own_pending" on public.poem_tags;

drop trigger if exists poem_tags_enforce_limit on public.poem_tags;

drop function if exists public.enforce_poem_tags_limit();

revoke all on table public.poem_tags from anon, authenticated;

-- poem_tags has no remaining dependents after policies/trigger/grants above.
drop table public.poem_tags;

drop policy if exists "tags_select_all" on public.tags;

revoke all on table public.tags from anon, authenticated;

-- tags no longer referenced by poem_tags.
drop table public.tags;

-- -----------------------------------------------------------------------------
-- 5–6) RLS + read-only access for poetry_types
-- -----------------------------------------------------------------------------

alter table public.poetry_types enable row level security;
alter table public.poetry_types force row level security;

create policy "poetry_types_select_all"
  on public.poetry_types
  for select
  to anon, authenticated
  using (true);

-- Intentional omission: no INSERT/UPDATE/DELETE policies for anon/authenticated.

grant select on table public.poetry_types to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 7) Poem security updates (preserve existing rules + immutable poetry type)
-- -----------------------------------------------------------------------------

-- Tighten INSERT RLS: poetry_type_id required; still own author + pending only.
drop policy if exists "poems_insert_own_pending" on public.poems;

create policy "poems_insert_own_pending"
  on public.poems
  for insert
  to authenticated
  with check (
    author_id = auth.uid()
    and status = 'pending'
    and poetry_type_id is not null
  );

-- Column privileges: clients insert only author/title/content/type.
-- Clients update only hide / soft-delete fields.
revoke insert on table public.poems from authenticated;
grant insert (author_id, title, content, poetry_type_id)
  on table public.poems to authenticated;

revoke update on table public.poems from authenticated;
grant update (is_hidden, deleted_at)
  on table public.poems to authenticated;

-- Replace insert guard: require poetry_type_id; do not invent a default type.
create or replace function public.enforce_poem_insert_guards()
returns trigger
language plpgsql
as $$
begin
  -- Privileged backends may insert freely; clients are constrained below.
  if coalesce(auth.role(), '') = 'service_role'
     or current_user in ('postgres', 'supabase_admin') then
    return new;
  end if;

  if auth.uid() is null then
    raise exception 'authentication required to create poems';
  end if;

  if new.author_id is distinct from auth.uid() then
    raise exception 'author_id must equal auth.uid()';
  end if;

  if new.poetry_type_id is null then
    raise exception 'poetry_type_id is required';
  end if;

  new.status := 'pending';
  new.is_hidden := coalesce(new.is_hidden, false);
  new.published_at := null;
  new.deleted_at := null;

  return new;
end;
$$;

comment on function public.enforce_poem_insert_guards() is
  'Forces pending client inserts with auth.uid() as author and a required poetry_type_id. Does not default the poetry type.';

-- Replace update guard: clients cannot change poetry_type_id after submission.
-- Privileged moderation path unchanged (published_at on first approval).
create or replace function public.enforce_poem_update_guards()
returns trigger
language plpgsql
as $$
declare
  is_privileged boolean;
begin
  -- Single BEFORE UPDATE trigger keeps poem update order deterministic.
  new.updated_at := now();

  is_privileged :=
    coalesce(auth.role(), '') = 'service_role'
    or current_user in ('postgres', 'supabase_admin');

  -- Privileged moderation path.
  -- When status becomes approved for the first time, stamp published_at.
  -- Do not overwrite an existing published_at on later privileged updates.
  if is_privileged then
    if new.status = 'approved'
       and old.status is distinct from 'approved'::public.poem_status
       and new.published_at is null then
      new.published_at := now();
    end if;
    return new;
  end if;

  -- Authenticated client path: protected columns stay immutable.
  if new.id is distinct from old.id then
    raise exception 'poems.id is immutable';
  end if;

  if new.author_id is distinct from old.author_id then
    raise exception 'poems.author_id is immutable';
  end if;

  if new.title is distinct from old.title
     or new.content is distinct from old.content then
    raise exception 'poem title and content cannot be edited after submission';
  end if;

  if new.status is distinct from old.status then
    raise exception 'poem moderation status cannot be changed by this role';
  end if;

  if new.published_at is distinct from old.published_at then
    raise exception 'published_at cannot be changed by clients';
  end if;

  -- Product rule: poetry type is chosen at submission and cannot change later.
  if new.poetry_type_id is distinct from old.poetry_type_id then
    raise exception 'poetry_type_id cannot be changed after submission';
  end if;

  if new.created_at is distinct from old.created_at then
    raise exception 'poems.created_at is immutable';
  end if;

  -- Soft-delete is one-way for clients: clearing deleted_at is not allowed.
  if old.deleted_at is not null
     and new.deleted_at is distinct from old.deleted_at then
    raise exception 'soft-deleted poems cannot be restored by clients';
  end if;

  return new;
end;
$$;

comment on function public.enforce_poem_update_guards() is
  'Client guard for protected poem columns including immutable poetry_type_id; privileged path sets published_at on first approval.';
